# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build_Test_and_Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_unit_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] #[18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checout the code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute Unit Tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo nadetto


  build_and_ui_tests:

    runs-on: ubuntu-latest
    needs: build_and_unit_tests

    strategy:
      matrix:
        node-version: [20.x]  #[18.x, 20.x, 22.x]
       
    steps:
    - name: Checout the code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start The Application with &
      #add & to keep the process in the background mode(to free the session) to be able to execute the tests
      run: npm run start &  
    - name: Execute Ui Tests
      run: npm run test:ui      